# Add Additional Effects to the spawned Zombie 
# BE VERY CAREFUL WITH SETTING THE EFFECTS as example: 
# if Increase_Damage is too high players die instantly without getting a deathscreen.
# They can still move but can't do anything else.

Effects:
  BLINDNESS: 0
  DAMAGE_RESISTANCE: 0
  FIRE_RESISTANCE: 0
  INCREASE_DAMAGE: 0
  INVISIBILITY: 0
  JUMP: 0
  POISON: 0
  REGENERATION: 0
  SLOW: 0
  SPEED: 0
  WATER_BREATHING: 0
  WEAKNESS: 0

# Define whether the spawned Zombie should pickup all Items from the player and drop them on death or not
# The Inventory does not contain the worn Armor
# The Armor does not contain the Player's head

CanPickupInventoryAndDrop: false
CanDropPlayerHead: false
CanDropArmor: false


# Define under which condition a Zombie should spawn
# Having all 3 Deathtypes will spawn a Zombie on every death
# Make sure that at least one condition is true, otherwise there will be no spawn at all

ZombieSpawnOnPvPDeath: true
ZombieSpawnOnPvEDeath: true
ZombieSpawnOnEnvironmentDeath: true