# Add Additional Effects to the spawned Zombie 
# BE VERY CAREFUL WITH SETTING THE EFFECTS as example: 
# if Increase_Damage is too high players die instantly without getting a deathscreen.
# They can still move but can't do anything else.

Effects:
  SPEED: 0
  SLOW: 0
  INCREASE_DAMAGE: 0
  DAMAGE_RESISTANCE: 0
  FIRE_RESISTANCE: 0
  JUMP: 0

# Define whether the spawned Zombie should pickup all Items from the player and drop them on death or not
CanDropEquip: false