name: ZombieResurrection
main: com.gmail.mikeundead.ZombieResurrection
version: 1.1.1
description: This plugin spawns a Zombie with your armor, weapon and face at your death location.
author: ASC_Dreanor
website: http://dev.bukkit.org/server-mods/zombieresurrection

permissions:
  zombieresurrection.*:
    description: Gives access to all ZombieResurrection commands
    default: op
  zombieresurrection.zombiespawn:
    description: Gives access to the Zombie spawn on death event
    default: true